name: flutter_klarna_inapp_sdk
description: Klarna&#x27;s Flutter wrapper for the In-App SDK
version: 0.0.4
homepage: https://github.com/klarna/flutter-klarna-inapp-sdk

environment:
  sdk: '>=2.14.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms: 
      android:
        package: com.klarna.inapp.sdk.flutter_klarna_inapp_sdk
        pluginClass: FlutterKlarnaInappSdk
      ios:
        pluginClass: FlutterKlarnaInappSdk

